version = 0.1
[default.deploy.parameters]
stack_name = "inventory-management-s3-stack"
resolve_s3 = true
s3_prefix = "inventory-management-s3-stack"
region = "af-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ProjectName=\"InventoryManagement\""
image_repositories = []
